# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Fletcher Howell
title: Honours Candidate in Computational Geodynamics
email: fletcher.howell@anu.edu.au
website: fletcherhowell.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: fmookowScience
github_username:  fletcherhowell
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: fmookow
# flickr_username: 
instagram_username: fmookow
linkedin_username: fletcherhowell
# xing_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: 
# orcid_username: 

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Headshot.jpg
about_content: | # this will include new lines to allow paragraphs
  Student with AProf Rhodri Davies. Commenced February 2021.
  Seismology and Mathematical Geophysics Group
  Research School of Earth Sciences
  The Australian National University 

  I am skilled in: <mark>Geodynamics</mark>, <mark>Geophysics</mark>, <mark>Geochemistry</mark>, <mark>python</mark>, and <mark>Physical Chemistry</mark>.

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Australian National University
        link: anu.edu.au
        # link_text: anu.edu.au
        sub_title: Student Recruitment Assistant (Senior Student Ambassador Scheme)
        caption: Janurary 2020 - December 2020
        description: | # this will include new lines to allow paragraphs
            Description from my resume.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Australian National University
        caption: 2017-Present
        sub_title: Bachelor of Science (Advanced)
        description: | # this will include new lines to allow paragraphs
            Major: Chemistry, Earth Science
            Minor: Science Communication

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
